import {Model} from 'objection';

import {BaseModel} from './baseModel';
import {User} from './user';

export class SshKey extends BaseModel {
    public id: string;
    public key: string; 
    public userId: string;
    public description: string;
    
    static get tableName() {
        return 'sshKeys';
    }

    autoGeneratedId() {
        return 'id';
    }

    static get jsonSchema() {
        return {
            type: 'Object',
            properties: {
                key: {type: 'string'},
                userId: {type: 'string'},
                description: {type: 'string'},
                createdAt: {type: 'string'},
                updatedAt: {type: 'string'}
            }
        };
    }

    static get relationMappings() {
        return {
            user: {
                relation: Model.BelongsToOneRelation,
                modelClass: User,
                join: {
                    from: 'sshKeys.userId',
                    to: 'users.id'
                }
            }
        };
    }
}