import {v4} from 'uuid';

import {BaseModel} from './baseModel';

export class User extends BaseModel {
    public id: string; 
    public username: string;
    public password: string;
    public firstName: string;
    public lastName: string;
    public email: string;
    
    static get tableName() {
        return 'users';
    }

    autoGeneratedId() {
        return 'id';
    }

    static get jsonSchema() {
        return {
            type: 'Object',
            properties: {
                id: {type: 'string'},
                username: {type: 'string'},
                password: {type: 'string'},
                firstName: {type: 'string'},
                lastName: {type: 'string'},
                createdAt: {type: 'string'},
                updatedAt: {type: 'string'},
                email: {type: 'string'}
            }
        };
    }
}