import {Model} from 'objection';

import {BaseModel} from './baseModel';
import {SshKey} from './sshKey';

export class User extends BaseModel {
    public id: string; 
    public username: string;
    public password: string;
    public firstName: string;
    public lastName: string;
    public email: string;
    
    static get tableName() {
        return 'users';
    }

    autoGeneratedId() {
        return 'id';
    }

    static get jsonSchema() {
        return {
            type: 'Object',
            properties: {
                id: {type: 'string'},
                username: {type: 'string'},
                password: {type: 'string'},
                firstName: {type: 'string'},
                lastName: {type: 'string'},
                createdAt: {type: 'string'},
                updatedAt: {type: 'string'},
                email: {type: 'string'},
                ownerUuid: {type: 'string'}
            }
        };
    }

    static get relationMappings() {
        return {
            sshKeys: {
                relation: Model.HasManyRelation,
                modelClass: SshKey,
                join: {
                    from: 'users.id',
                    to: 'sshKeys.userId'
                }
            }
        };
    }
}