import {Model} from 'objection';
import {BaseModel} from './baseModel';
import {User} from './user';

export class VlanId extends BaseModel {
    public id: string;
    public vlanId: number; 
    public ownerUuid: string;
    
    static get tableName() {
        return 'vlanIds';
    }

    autoGeneratedId() {
        return 'id';
    }

    static get jsonSchema() {
        return {
            type: 'Object',
            properties: {
                vlanId: {type: 'number'},
                ownerUuid: {type: 'string'},
                createdAt: {type: 'string'},
                updatedAt: {type: 'string'}
            }
        };
    }

    static get relationMappings() {
        return {
            user: {
                relation: Model.BelongsToOneRelation,
                modelClass: User,
                join: {
                    from: 'vlanIds.ownerUuid',
                    to: 'users.ownerUuid'
                }
            }
        };
    }
}