const Model = require('objection').Model;
const uuid = require('uuid');

class BaseModel extends Model {
    $beforeInsert(context) {
        const parent = super.$beforeInsert(context);

        return Promise.resolve(parent)
            .then(() => {
                this.createdAt = new Date();
                this.updatedAt = new Date();

                if (this.autoGeneratedId && !this[this.autoGeneratedId()]) {
                    this[this.autoGeneratedId()] = uuid.v4();
                }
            });
    }

    $beforeUpdate(opt, context) {
        const parent = super.$beforeUpdate(opt, context);

        return Promise.resolve(parent)
            .then(() => {
                this.updatedAt = new Date();
            });
    }
}

module.exports = BaseModel;